### ISSUE TITLE
Date picker style

### ISSUE THREAD

**Issue by averlius** [bikasv/cordova-android-plugins#14]
Hi, i really found this plugin useful,but for some reason it is showing the old date picker style, i have tested it in lg g3 and in some samsung, i dont know why it does not show the one you posted in your tutorial.
Thanks

**Comment by bikasv** [comment]
It's because of the theme applied to your app. Please look into AndroidManifest.xml file in your project (<Your_Project>/platforms/android/AndroidManifest.xml).

You'll find the default applied theme is `android:theme="@android:style/Theme.Black.NoTitleBar"`
You can change it to`android:theme="@android:style/Theme.Black.NoTitleBar"` for the look of latest calendar in the demo. Also, if your app doesn't depend on modified themes, then just delete this portion of code and best theme for the device will be picked and correct calendar will be shown.

Also, Cordova by default uses following for API selection

  `<uses-sdk android:minSdkVersion="10" android:targetSdkVersion="22" />`

I suggest you to use following instead, as targeting below Kitkat doesn't makes much sense

  `<uses-sdk android:minSdkVersion="17" android:targetSdkVersion="22" />`
